### ISSUE TITLE
Convert router to use Dash

### ISSUE THREAD

**Issue by GeeH** [ezimuel/zend-stratigility-dispatch#2]
Would you be open to use the Dash router once the PR to make it PSR-7 compliant has been merged?

**Comment by ezimuel** [comment]
@GeeH I'm thinking to open the routing part with a more general solution, based on a common interface and adapters, with Dash router included. Moreover, also Aura.router will be PSR-7 compliant with 3.x version.

**Comment by ezimuel** [comment]
@GeeH I just pushed an update of the dispatcher that support a routing adapter system. I provided the Aura adapter and I would like to add others like Dash in the future. Moreover, I also supported the [Container Interoperability](https://github.com/container-interop/container-interop) project to support the injection of a Container in the dispatcher. In this way you can specify an action as name of a container object.
