### ISSUE TITLE
Rename getMatchedAction()

### ISSUE THREAD

**Issue by weierophinney** [ezimuel/zend-stratigility-dispatch#6]
Per discussion, I think we should rename `RouterInterface::getMatchedAction()` to `getMatchedMiddleware()`, to better describe what the method is intended to return.

**Comment by weierophinney** [comment]
Or "callable". :)

**Comment by mwillbanks** [comment]
:+1: certainly agree :)

**Comment by ezimuel** [comment]
@mwillbanks I'm going to remove this repository in favor of https://github.com/zendframework/zend-expressive
